version: "3.3"

services:
  zookeeper:
    image: wurstmeister/zookeeper 
    container_name: zookeeper 
    ports:
      - 2181:2181 

  broker1:
    image: wurstmeister/kafka
    container_name: kafka-broker-1
    hostname: broker1 
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=broker1 
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_LISTENERS=PLAINTEXT://broker1:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker1:9092
    depends_on:
      - zookeeper

  broker2:
    image: wurstmeister/kafka
    container_name: kafka-broker-2
    hostname: broker2
    ports:
      - 9093:9093
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=broker2 
      - KAFKA_ADVERTISED_PORT=9093
      - KAFKA_LISTENERS=PLAINTEXT://broker2:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker2:9093
    depends_on:
      - zookeeper

  broker3:
    image: wurstmeister/kafka
    container_name: kafka-broker-3
    hostname: broker3
    ports:
      - 9094:9094
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=broker3
      - KAFKA_ADVERTISED_PORT=9094
      - KAFKA_LISTENERS=PLAINTEXT://broker3:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker3:9094
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=broker1:9092, broker2:9093, broker3:9094
      - JVM_OPTS=-Xmx64M
    depends_on:
      - broker1
      - broker2
      - broker3