version: "3.3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper 
    ports:
      - 2181:2181 
    networks:
      - kafkanet
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  broker1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-1
    ports:
      - 29092:29092
      - 39092:39092
    networks:
      - kafkanet
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, SAME_EXTERNAL:PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://:9092, SAME_EXTERNAL://:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://broker1:9092, SAME_EXTERNAL://localhost:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 # This is required when you are running with a single-node cluster
    depends_on:
      - zookeeper

networks:
  kafkanet:
    name: kafkanetlayer
    